// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37wRHxWyOE32A9fhRioVPlg_VAEF2CEI',
    appId: '1:562848883140:web:28462bfdb76fa11ddc8491',
    messagingSenderId: '562848883140',
    projectId: 'login-weather-83e73',
    authDomain: 'login-weather-83e73.firebaseapp.com',
    storageBucket: 'login-weather-83e73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vxov11NNZFNAAHXB8_vwpIOGOvH16GE',
    appId: '1:562848883140:android:9fc162cf96072ba5dc8491',
    messagingSenderId: '562848883140',
    projectId: 'login-weather-83e73',
    storageBucket: 'login-weather-83e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_y3vyykY2kMsP3c-Xo4Xck39HhvM378M',
    appId: '1:562848883140:ios:e003a5c8ac87a3aedc8491',
    messagingSenderId: '562848883140',
    projectId: 'login-weather-83e73',
    storageBucket: 'login-weather-83e73.appspot.com',
    iosClientId: '562848883140-qe24d2lg7k5evoe57i74c0nhra5p8vqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_y3vyykY2kMsP3c-Xo4Xck39HhvM378M',
    appId: '1:562848883140:ios:e003a5c8ac87a3aedc8491',
    messagingSenderId: '562848883140',
    projectId: 'login-weather-83e73',
    storageBucket: 'login-weather-83e73.appspot.com',
    iosClientId: '562848883140-qe24d2lg7k5evoe57i74c0nhra5p8vqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );
}
